### ISSUE TITLE
No support for `if: runner.os == 'OSName'` or it works incorrectly

### ISSUE THREAD

**Issue by kafeg** [ChristopherHX/github-act-runner#57]
Hello! Looks like the check in the title works not always. For e.g.:

This works correctly and skipped on Unix
```
...
steps:
  - name: Set MSVC parameters
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: ${{ matrix.arch }}
```

But this executed on macOS when it should not:
```
...
steps:
  - name: Download/unpack ARM-Linux dependencies (Unix/Bash)
        if: runner.os == 'Linux'
        run: |
          ls
          ...
```
