### ISSUE TITLE
GITHUB_OUTPUT broken in nodejs actions via toolkit (0.4.0-0.4.1)

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/github-act-runner#90]
run steps and old syntax are working ..., investigating.

example workflow
```yaml
on: push
jobs:
  _:
    runs-on: act-cache
    steps:
    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: path/to/dependencies
        key: mycache-test
    - run: |
        mkdir -p path/to/dependencies
        echo "hello world " > path/to/dependencies/hello.txt
        echo "$GITHUB_CTX" > path/to/dependencies/ctx.txt        
      env:
        GITHUB_CTX: ${{ tojson(github) }}
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    - uses: actions/cache/save@v3
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      with:
        path: path/to/dependencies
        key: mycache-test
    - run: cat path/to/dependencies/hello.txt
    - run: cat path/to/dependencies/ctx.txt
    - run: ${{ tojson(steps) }}
      shell: cat {0}
```

problem cache-hit is always unset
